title: |
  VNUHCM – University of Science
  Faculty of Information Technology

reporttitle: "REPORT"
subtitle: "Lab 2: Edge Detection"

author: "23127266 – Nguyen Anh Thu"

advisor: |
  Prof. Dr. Ly Quoc Ngoc
  MSc. Nguyen Manh Hung
  MSc. Pham Thanh Tung

date: "2025"
